name: 'Cache Dependencies'
description: 'Get the dependencies and cache them'
inputs:
  caching:
    description: 'Enable caching of dependencies'
    required: false
    default: 'true'
    type: boolean
    options:
      - true
      - false
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
